# Generated by Django 4.2.7 on 2023-12-02 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redirect",
            options={
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
            },
        ),
    ]
