# Generated by Django 4.2.7 on 2023-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0002_alter_redirect_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="password_that_will_requested_to_redirect",
                max_length=128,
                null=True,
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="validity_clicks",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="how_many_click_on_link_will_be_valid",
                null=True,
                verbose_name="valid_click_number",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="validity_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=90,
                help_text="how_many_day_link_will_be_valid",
                null=True,
                verbose_name="valid_day_number",
            ),
        ),
    ]
