# Generated by Django 4.2.14 on 2024-08-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0003_alter_redirect_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="create_method",
            field=models.CharField(
                blank=True,
                choices=[("API", "API"), ("WEB", "Web")],
                default="WEB",
                help_text="method_which_redirect_was_created",
                max_length=20,
                null=True,
                verbose_name="create_method",
            ),
        ),
        migrations.AddField(
            model_name="redirect",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                default=None,
                help_text="client_ip_address_who_created_redirect",
                null=True,
                verbose_name="ip_address",
            ),
        ),
        migrations.AddField(
            model_name="redirect",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="is_active", verbose_name="active"
            ),
        ),
    ]
