# Generated by Django 4.2.14 on 2024-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0005_redirect_deactivated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="create_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("API", "API"),
                    ("WEB", "Web"),
                    ("WEB+FILE", "Web_by_file"),
                ],
                default="WEB",
                help_text="method_which_redirect_was_created",
                max_length=20,
                null=True,
                verbose_name="create_method",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="deactivated_at",
            field=models.DateTimeField(
                default=None,
                help_text="when_bond_was_deactivated",
                null=True,
                verbose_name="deactivation_time",
            ),
        ),
    ]
