# Generated by Django 5.2.17 on 2026-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0006_alter_redirect_create_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirect",
            name="create_method",
            field=models.CharField(
                choices=[
                    ("API", "API"),
                    ("WEB", "Web"),
                    ("WEB+FILE", "Web_by_file"),
                ],
                default="WEB",
                help_text="method_which_redirect_was_created",
                max_length=20,
                verbose_name="create_method",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when_bond_was_deactivated",
                null=True,
                verbose_name="deactivation_time",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="password_that_will_requested_to_redirect",
                max_length=128,
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="short_link",
            field=models.SlugField(
                allow_unicode=True,
                help_text="shorten_link_to_redirect_to_resource",
                unique=True,
                verbose_name="short_link",
            ),
        ),
    ]
