# Generated by Django 4.2.7 on 2023-12-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0002_alter_redirect_options"),
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="redirect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="redirects.redirect",
            ),
        ),
    ]
