# Generated by Django 4.2.8 on 2023-12-18 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0005_alter_click_redirect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="click",
            name="referrer",
        ),
    ]
