# Generated by Django 5.2.17 on 2026-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0006_remove_click_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="browser",
            field=models.TextField(
                blank=True,
                default="",
                help_text="browser_from_which_redirect_was_made",
                verbose_name="browser",
            ),
        ),
        migrations.AlterField(
            model_name="click",
            name="city",
            field=models.TextField(
                blank=True,
                default="",
                help_text="city_from_which_redirect_was_made",
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="click",
            name="country",
            field=models.TextField(
                blank=True,
                default="",
                help_text="country_from_which_redirect_was_made",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="click",
            name="os",
            field=models.TextField(
                blank=True,
                default="",
                help_text="operating_system_from_which_redirect_was_made",
                verbose_name="os",
            ),
        ),
    ]
