# Generated by Django 4.2.13 on 2024-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_regex",
                    models.CharField(
                        help_text="domain_regex_that_will_be_prohibited_from_shortening",
                        max_length=255,
                        verbose_name="domain_regex",
                    ),
                ),
            ],
        ),
    ]
