# Generated by Django 4.2.13 on 2024-07-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockeddomain",
            options={
                "verbose_name": "domain_regex",
                "verbose_name_plural": "domains_regex",
            },
        ),
    ]
