server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name datanar.ru www.datanar.ru;

    ssl_certificate /etc/letsencrypt/live/datanar.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/datanar.ru/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/datanar.ru/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    http2 on;

    include /etc/nginx/projects/datanar/include/datanar.locations.conf;
}
