name: Python application

on:
  push:
    branches: [ "master", "develop", "artem", "sergey", "vladimir", "for_merge"]
  pull_request:
    branches: [ "master", "develop", "artem", "sergey", "vladimir", "for_merge"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Lint with flake8
      run: |
        cd ./datanar
        flake8 . --config=.flake8
    - name: Lint with black
      run: |
        cd ./datanar
        black . --check --verbose --diff --line-length 79
    - name: Django testing
      run: |
        cd ./datanar
        python manage.py test
