name: Datanar

on:
  push:
    branches: [ "main", "dev", "artem", "sergey", "vladimir", "for_merge"]
  pull_request:
    branches: [ "main", "dev", "artem", "sergey", "vladimir", "for_merge"]

permissions:
  contents: read

jobs:
  black-test:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install black
      - name: Check code formatting with black
        run: black ./datanar/ --check --verbose --diff

  flake8-test:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install -r requirements/test.txt
    - name: Check code formatting with flake8
      run: flake8 ./datanar/

  django-test:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements/dev.txt
      - name: Run Django tests
        run: |
          cd ./datanar
          python manage.py test

  prod-deploy:
    if: github.ref == 'refs/heads/main'
    needs: [black-test, flake8-test, django-test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/datanar
          git reset --hard origin/main  
          git pull origin main
          docker compose down -v
          docker compose up --build -d